### ISSUE TITLE
Constants from settings not resolved

### ISSUE THREAD

**Issue by matejsp** [typeddjango/django-stubs#1614]
# Bug report
It seems that if follow_imports = skip then the settings is not resolved.

## What's wrong

settings.py
```
READ_ONLY_DB = 'read_only'
ORDER_LOG_DB = READ_ONLY_DB
TRADING_DB = READ_ONLY_DB
READ_BINLOG_DB = 'read_binlog_replica'
SECRET_KEY = '<TAG>'  # nosec

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sample'
]
```

```
(.venv) ➜  bug_report2 mypy sample                     
sample/document_revision.py:13: error: 'Settings' object has no attribute 'READ_ONLY_DB'  [misc]
Found 1 error in 1 file (checked 3 source files)
```

```
[mypy]
follow_imports = skip

files =
    sample/

plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
DJANGO_SETTINGS_MODULE = settings
```

Workaround that works:
```
[mypy-settings]
follow_imports = normal
```

This worked in 1.7.0.

## System information

- OS:
- `python` version: 3.11
- `django` version: 4.2.3
- `mypy` version: 1.4.1
- `django-stubs` version: 4.2.3
- `django-stubs-ext` version: 4.2.2

**Comment by matejsp** [comment]
This is reproducible test:
untar & run: runme
it creates venv with python 3.11, installs packages and run mypy (check it before running)

[bug_report.tar.gz](https://github.com/typeddjango/django-stubs/files/11971418/bug_report.tar.gz)

**Comment by matejsp** [comment]
Another issue with resolving settings that are imported a bit differently between django-stubs 4.2.3 and 1.7.0 (last working for us).

so we have tree structure for settings:
```
conf/settings_base.py
conf/development/settings_base.py
conf/development/mac/settings_base.py
conf/development/docker/settings_base.py
conf/testing/settings_base.py
conf/testing/jenkins/settings_base.py
```

settings.py:
```
from conf.development.mac import settings
for setting in dir(settings):
    if setting == setting.upper():
        globals()[setting] = getattr(settings, setting)
```

So each file in hierarchy imports settting that way.

mypy with django stubs (not resolving the settings:
```
from conf.development import settings_base
for setting in dir(settings_base):
    if setting == setting.upper():
        globals()[setting] = getattr(settings_base, setting)
```

however it works with:
```
from conf.settings_base import *
```

but this imports also other imports like constants.py in settings_base.

**Comment by sobolevn** [comment]
Please, try our `strict_settings` flag https://github.com/typeddjango/django-stubs#how-to-use-a-custom-library-to-handle-django-settings

If it does not work for you, feel free to reopen :)
