### ISSUE TITLE
[5.0.3 regression] Can’t `filter` a `QuerySet` on an `alias`

### ISSUE THREAD

**Issue by andersk** [typeddjango/django-stubs#2302]
```py
from django.db import models

class Blog(models.Model):
    pass

class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

def test() -> None:
    Blog.objects.alias(entries=models.Count("entry")).filter(entries__gt=5)
```

```
my_app/models.py:13: error: Cannot resolve keyword 'entries' into field. Choices are: entry, id  [misc]
Found 1 error in 1 file (checked 3 source files)
```

This was introduced by a28717df356fb767efb2d832b9146f759fd8cfd9 (#2277).

**Comment by flaeppe** [comment]
I don't know if we should call this a regression? Any version prior to `5.0.3` just didn't try to check the `filter` call.

At least there's no plugin code that tries to do anything with `alias`

**Comment by andersk** [comment]
From a user perspective, this was allowed in 5.0.2 and incorrectly disallowed in 5.0.3. Whatever you’d like to call it, we can’t upgrade to django-stubs ≥ 5.0.3 in [Zulip](https://github.com/zulip/zulip) until it’s addressed.

**Comment by sobolevn** [comment]
Really interesting: there are no handlers for `alias` in https://github.com/typeddjango/django-stubs/blob/b76f9f4d9d4f8b4ce8f0f9f0938c81faaafc25c6/mypy_django_plugin/main.py#L168-L181

I will start digging into this!

**Comment by sobolevn** [comment]
The problem happens because we use `entries__gt=5` in `filter`, which should be allowed. We need to add `alias()` support and infer field names from there.
