### PR TITLE
Treat `QuerySet.alias` like `QuerySet.annotate`

### LINKED ISSUE #2302: [5.0.3 regression] Can’t `filter` a `QuerySet` on an `alias`
```py
from django.db import models

class Blog(models.Model):
    pass

class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

def test() -> None:
    Blog.objects.alias(entries=models.Count("entry")).filter(entries__gt=5)
```

```
my_app/models.py:13: error: Cannot resolve keyword 'entries' into field. Choices are: entry, id  [misc]
Found 1 error in 1 file (checked 3 source files)
```

This was introduced by a28717df356fb767efb2d832b9146f759fd8cfd9 (#2277).

### PR DESCRIPTION
**Pull request by andersk**
Although this incorrectly allows some misuses of `alias` that only work at runtime with `annotate`, that is better than incorrectly forbidding all uses of `alias`.

- Fixes #2302.

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks! Further improvements of `alias()` are welcome!
