### PR TITLE
Do `models.Model` adjustments from `get_metaclass_hook`

### LINKED ISSUE #2304: [5.0.3 regression] error: "type[RealmFilter]" has no attribute "objects"  [attr-defined]
When trying to upgrade to django-stubs 5.0.3 or 5.0.4 in [Zulip](https://github.com/zulip/zulip), I get 25 unexpected errors like `error: "type[RealmFilter]" has no attribute "objects"  [attr-defined]`. This is not #1684; `RealmFilter` is a normal concrete model class. The issue seems to depend on the structure of the project’s import graph.

Based on `git bisect`, it first occurs at

- 2f5a4946e0569e9bc69729fc59794a1ea4347b91 (#2276, cc @asottile).

I’ve reduced the issue to this minimized test case: https://github.com/andersk/no-attribute-objects

```console
$ mypy .
zerver/models/__init__.py:6: error: "type[RealmFilter]" has no attribute "objects"  [attr-defined]
Found 1 error in 1 file (checked 10 source files)
```

**`pyproject.toml`**

```toml
[tool.django-stubs]
django_settings_module = "zproject.settings"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
```

**`confirmation/__init__.py`** (empty)

**`confirmation/models.py`**

```python
from django.db import models

from zerver.models import Realm


class Confirmation(models.Model):
    realm = models.ForeignKey(Realm, on_delete=models.RESTRICT)
```

**`zerver/__init__.py`** (empty)

**`zerver/models/__init__.py`**

```python
from zerver.models.linkifiers import RealmFilter as RealmFilter
from zerver.models.realms import Realm as Realm
from zerver.models.streams import Stream as Stream
from zerver.models.users import UserProfile as UserProfile

RealmFilter.objects
```

**`zerver/models/linkifiers.py`**

```python
from django.db import models


class RealmFilter(models.Model):
    pass
```

**`zerver/models/realms.py`**

```python
from django.db import models


class Realm(models.Model):
    pass
```

**`zerver/models/streams.py`**

```python
from django.db import models

from zerver.models.realms import Realm
from zerver.models.users import UserProfile


class Stream(models.Model):
    realm = models.ForeignKey(Realm, on_delete=models.RESTRICT)
    creator = models.ForeignKey(UserProfile, on_delete=models.RESTRICT)
```

**`zerver/models/users.py`**

```python
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin


class UserProfile(AbstractBaseUser, PermissionsMixin):
    pass
```

**`zproject/__init__.py`** (empty)

**`zproject/settings.py`**

```python
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "confirmation",
    "zerver",
]
```

### PR DESCRIPTION
**Pull request by flaeppe**
The called hook expects/wants the class body analyzed, but the `get_customize_class_mro_hook` hook, that it was previously called from, invokes the hook before the class body has been analyzed..

Docs: https://mypy.readthedocs.io/en/stable/extending_mypy.html#current-list-of-plugin-hooks

> __get_customize_class_mro_hook()__ can be used to modify class MRO (for example insert some entries there) before the class body is analyzed.

## Related issues

- Closes #2304 
- Refs #2280

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks! I think that we didn't have this hook back in the days of the original code.
