### ISSUE TITLE
Accessing `.objects` on variable typed `type[Model]` gives error: `type[Model]" has no attribute "objects"`

### ISSUE THREAD

**Issue by richardebeling** [typeddjango/django-stubs#1685]
After updating django-stubs from 4.2.3 to 4.2.4, this code:
```python3
from django.db.models import Model

def test(SomeModel: type[Model]):
    SomeModel.objects.all()
```

produces this output when running `mypy test.py`:
```
test.py:4: error: "type[Model]" has no attribute "objects"  [attr-defined]
```

It passed typechecking with 4.2.3. According to [django's documentation on Model attributes](https://docs.djangoproject.com/en/4.2/topics/db/models/#model-attributes), `objects` should be accessible on models unless the model has a custom manager.

The release notes for 4.2.4 don't indicate to me that this was changed. Was this change intentional? If yes, how should I annotate `test` above to make clear that it expects some model class with the default `objects` manager attribute?

## System information

- OS: ubuntu 22.04
- `python` version: 3.10.12
- `django` version: 4.2.3
- `mypy` version: 1.4.1
- `django-stubs` version:  4.2.4
- `django-stubs-ext` version:  4.2.2

**Comment by flaeppe** [comment]
Duplicate of #1684

**Comment by richardebeling** [comment]
Ah, thanks. I'd argue the release notes should mention this as a possibly breaking change, since code that passed type checking before now fails. django-stubs 4.2.4 has this bullet point in the [release notes](https://github.com/typeddjango/django-stubs/releases/tag/4.2.4):

> We also update our stubs to be compatible with Django 4.2.5 (and all prior versions of 4.2).

but django doesn't seem to have changed their policy regarding `.objects` in the 4.1 -> 4.2 update, so imho the bullet point doesn't "justify" higher strictness regarding `.objects` on models.

What do you think?

**Comment by flaeppe** [comment]
Yeah maybe we should've been more clear in the release notes.

I think the bullet point aims for all prior 4.x versions of `Django`, not `django-stubs`? Not sure I follow otherwise

I'd argue that this improved alignment with the runtime justifies a breaking change. I'd say the new version just found a bug.

And I don't think the behavior regarding `objects` is anything new for the 4.x series. But perhaps we've found an ambiguity in the Django documentation?

**Comment by richardebeling** [comment]
I see how my last post was a bit ambiguous, I edited it to make it a bit clearer.

In the end, I'm only suggesting to add an additional bullet point in the release notes, something along the lines of:
* We no longer assume the `objects` attribute to be present on generic `Model` classes. As per the [django documentation](https://docs.djangoproject.com/en/4.2/topics/db/managers/#django.db.models.Model._default_manager), code working with generic models should use the `_default_manager` attribute instead.

**Comment by sobolevn** [comment]
Done!
