### ISSUE TITLE
`Unable to resolve type of choices property` for `.value` on Choices

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#2643]
# Bug report

here's a small example from sentry:

```python
from django.db import models

class ComparisonDeltaChoices(models.IntegerChoices):
    FIVE_MINUTES = (300, "5 minutes ago")
    FIFTEEN_MINUTES = (900, "15 minutes ago")
    ONE_HOUR = (3600, "1 hour ago")
    ONE_DAY = (86400, "1 day ago")
    ONE_WEEK = (604800, "1 week ago")
    ONE_MONTH = (2592000, "1 month ago")


print([choice.value for choice in ComparisonDeltaChoices])
```

## What's wrong

```console
$ mypy t3.py
t3.py:12: error: Unable to resolve type of choices property  [misc]
Found 1 error in 1 file (checked 1 source file)
```

## How is that should be

should resolve as `int`

## System information

- OS:
- `python` version: 3.13.1
- `django` version: 5.1.7
- `mypy` version: 1.15.0
- `django-stubs` version: 5.2.0 (well, technically patched 5.2.0)
- `django-stubs-ext` version: 5.2.0

**Comment by asottile-sentry** [comment]
likely regressed in #2582 

cc @ngnpope

**Comment by ngnpope** [comment]
Thanks for the report. I'm already working on a fix.

**Comment by asottile-sentry** [comment]
#2644 fixes this particular case fwiw

**Comment by ngnpope** [comment]
Thanks. I've got something that fixes a bunch of other related issues as well as this one. I'll have it up for review tomorrow.
