### ISSUE TITLE
New "has no field named" error after upgrading to 5.2.3+ (missing a deferral?)

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#2833]
# Bug report

apologies I haven't been able to narrow this down yet -- but it appears only after upgrading:

```
src/sentry/models/group.py:87: error: Group has no field named 'short_id'  [misc]
```

however this model does have this field:
- https://github.com/getsentry/sentry/blob/0fb99c104713410075b9be24d4882f73564cd4aa/src/sentry/models/group.py#L87
- https://github.com/getsentry/sentry/blob/0fb99c104713410075b9be24d4882f73564cd4aa/src/sentry/models/group.py#L634

debugging it looks like the symbol *does* exist but may need a deferral pass?

around hereish: https://github.com/typeddjango/django-stubs/blob/82c99e83e3406fad91d43ff8fdc920df08f8d46f/mypy_django_plugin/django/context.py#L88
```
((Pdb)) info.get(field_name)
<mypy.nodes.SymbolTableNode object at 0x14a1e0310>
((Pdb)) info.get(field_name).node
<Var 'sentry.models.group.Group.short_id' at 0x14a1cfe20>
((Pdb)) info.get(field_name).node.type  # None
((Pdb)) info.get(field_name).node.is_ready
False
```

(`Var` being a not-yet-resolved alias I believe?)

## System information

- OS:
- `python` version: 3.13.1
- `django` version: modern
- `mypy` version: 1.17.1
- `django-stubs` version: 5.2.5 (forked)
- `django-stubs-ext` version: 5.2.5

**Comment by asottile-sentry** [comment]
I believe this regressed (?) in ed7b2b6b4f24a20000eb86a29a1b8aa69b218c11 cc @UnknownPlatypus 

though I am having quite the time bisecting due to the fork :S

**Comment by UnknownPlatypus** [comment]
> though I am having quite the time bisecting due to the fork :S

Understandable :s, I've mostly reused an internal helper but I believe you're right with the line 88 that should probably trigger a deferral instead of a simple return None that is mistaken as a "there is no field here"

If you can come up with a yml test reproducing this behavior that would be awesome. I'll give it a shot otherwise when I get some time

**Comment by asottile-sentry** [comment]
I'm not sure if it's related but this test-only (not installed) model also started erroring:

```
tests/sentry/db/models/fields/bitfield/test_bitfield.py:192: error: BitFieldTestModel has no field named 'flags'  [misc]
```

**Comment by HansAarneLiblik** [comment]
Hi. Not sure if this is related to this issue, but I'm having similar problem with ManyToManyField relation when querying "backwards"

Started happening after upgrading from django-stubs 5.2.2 to 5.2.3+ (Issue persisted on all the next releases) 

```py 
# Create your models here.
class Voters(models.Model):
    national_id = models.IntegerField()
    name = models.CharField(max_length=200)

class Polls(models.Model):
    name = models.CharField(max_length=200)
    year = models.IntegerField()
    voters = models.ManyToManyField(Voters)

def func() -> None:
    # Works, as `voters` is defined in this model
    a = Polls.objects.prefetch_related('voters').all()
    print(a)
    # Errors, as this is "backwards" call
    # Cannot find "polls" on "Voters" object, "polls" is an invalid parameter to "prefetch_related()"  [misc]
    b = Voters.objects.prefetch_related('polls').all()
    print(b)
```

**Comment by UnknownPlatypus** [comment]
@HansAarneLiblik Your code is a runtime error and correctly flagged by django-stubs here. 
The [automatically generated](https://docs.djangoproject.com/en/5.2/topics/db/examples/many_to_many/) reverse lookup is `polls_set`.so you should be doing: `b = Voters.objects.prefetch_related('polls_set').all()`

```python
func()
<QuerySet []>
Traceback (most recent call last):
  File "/home/thibaut/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-bd1982955a12>", line 1, in <module>
    func()
  File "<ipython-input-2-715678155918>", line 8, in func
    print(b)
  File "/home/thibaut/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 376, in __repr__
    data = list(self[: REPR_OUTPUT_SIZE + 1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thibaut/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/home/thibaut/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1888, in _fetch_all
    self._prefetch_related_objects()
  File "/home/thibaut/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1275, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/home/thibaut/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 2301, in prefetch_related_objects
    raise AttributeError(
AttributeError: Cannot find 'polls' on Voters object, 'polls' is an invalid parameter to prefetch_related()
```

**Comment by HansAarneLiblik** [comment]
Nice, you're right! The mypy error disappears, but I'm pretty sure we're using this syntax (without `_set` or `related_name`) in our production code 🥹

**Comment by UnknownPlatypus** [comment]
> The mypy error disappears, but I'm pretty sure we're using this syntax (without _set or related_name) in our production code 🥹

If the QuerySet is empty, it does not raise but is a latent bug waiting to happen. Otherwise, you might have found some dead code I suppose.
But if you find cases where it's correct at runtime, feel free to open a new issue with a minimal reproducible exemple

**Comment by HansAarneLiblik** [comment]
Aha, we used `Voters.objects.prefetch_related('polls').values_list('polls__name', flat=True)`. This works with both styles, but indeed, using `_set` is proper!

And this is the case, which mypy flagged

But in this case, prefetch is not even necessary!
