### ISSUE TITLE
regression in 5.2? cannot extract `rest_framework` `Response` from django test client

### ISSUE THREAD

**Issue by asottile-sentry** [typeddjango/django-stubs#2683]
# Bug report

seems something in 5.2 caused this to break -- here's a minimal example:

```python
from django.test import TestCase
from rest_framework.response import Response


class T(TestCase):
    def get_rf_resp(self, url: str) -> Response:
        resp = self.client.get(url)
        assert isinstance(resp, Response), resp
        return resp
```

## What's wrong

```console
$ mypy t3.py --warn-unreachable
t3.py:8: error: Subclass of "_MonkeyPatchedWSGIResponse" and "Response" cannot exist: would have incompatible method signatures  [unreachable]
t3.py:9: error: Statement is unreachable  [unreachable]
Found 2 errors in 1 file (checked 1 source file)
```

## How is that should be

no errors

## System information

- OS:
- `python` version: 3.13.1
- `django` version: 5.2.0
- `mypy` version: 1.15.0
- `django-stubs` version: 5.2.0 (forked, but not relevant here)
- `django-stubs-ext` version: 5.2.0

**Comment by asottile-sentry** [comment]
bisected to #2509

**Comment by asottile-sentry** [comment]
5.2.1 I have a similar problem now with StreamingHttpResponse:

```
tests/sentry/api/test_base.py:495: error: Subclass of "Response" and "StreamingHttpResponse" cannot exist: would have incompatible method signatures  [unreachable]
```

**Comment by asottile-sentry** [comment]
bisected to 08cdfe576d62fc3a2dfc33197a3260cb0a0dc097 #2654 cc @UnknownPlatypus 

used this:

```python
from rest_framework.response import Response
from django.http.response import StreamingHttpResponse

x: Response
if isinstance(x, StreamingHttpResponse):
    print(1)
```

and `git bisect run bash -c 'cd .. && mypy t.py --warn-unreachable || exit 1'`

**Comment by asottile-sentry** [comment]
apparently for that one it is the `def content(self) -> NoReturn: ...` property

**Comment by UnknownPlatypus** [comment]
Thanks @asottile-sentry for the detailed bug report and bisection. 
For the initial issue, I've submitted a fix in #2737

As for the second issue, the `content` property is conflicting between drf "Response" and django "StreamingHttpResponse".

``` python
# django
class StreamingHttpResponse:
    def content(self) -> NoReturn: ...

# drf
class Response:
    def content(self) -> bytes: ...
```

So I'm not sure what's the good way forward, it seem that it could catch actual issues ? 
Otherwise, removing `def content(self) -> NoReturn: ...` from django-stubs is probably fine, it does not add much safeguards versus not beeing defined.
