### ISSUE TITLE
order_by refuses JSONField transforms

### ISSUE THREAD

**Issue by cjwatson** [typeddjango/django-stubs#3457]
# Bug report

## What's wrong

I think this was introduced by #3178, although I'm guessing a bit.

`models.py` in a test project:
```python
from django.db import models

class Item(models.Model):
    data = models.JSONField()

Item.objects.order_by("data__field")
```

```console
$ uv run -p 3.14 -w 'django-stubs==6.0.0,mypy' mypy src
src/ds/models.py:8: error: Cannot resolve keyword 'field' into field or transform on 'data'.  [misc]
Found 1 error in 1 file (checked 8 source files)
```

This is fine at run-time, and turns into a JSON transform.  I've reduced this from a project that I'm currently trying to upgrade from django-stubs 5.2.9 (where this worked) to 6.0.6; it's reproducible with all versions between 6.0.0 and 6.0.6 inclusive.

## How is that should be

```console
$ uv run -p 3.14 -w 'django-stubs==5.2.9,mypy' mypy src
Success: no issues found in 8 source files
```

## System information

- OS:
- `python` version: 3.14.6
- `django` version: 5.2.15
- `mypy` version: 2.1.0
- `django-stubs` version: 6.0.6
- `django-stubs-ext` version: 6.0.6

**Comment by cjwatson** [comment]
I seem to be able to work around this by transforming `.order_by("foo__bar")` into `.annotate(bar=F("foo__bar")).order_by("bar")`, although this is a bit cumbersome and I don't think I should have to.

**Comment by sobolevn** [comment]
PR is welcome :)

**Comment by cjwatson** [comment]
I'd have no idea where to start in this case, sorry!  Maybe @federicobond has some idea?

**Comment by federicobond** [comment]
I do! It turned out to be a relatively simple fix.
