### ISSUE TITLE
5.2.3 arg-type complaint for QuerySet.union

### ISSUE THREAD

**Issue by alexpilcher** [typeddjango/django-stubs#2825]
# Bug report

Hi,
Our project uses `union` to merge two querysets. This line of code now causes an `arg-type` complaint from MyPy after updating django-stubs to 5.2.3 or later (no issue when using 5.2.2). 

The pattern is lifted directly from the Django documentation for union:
https://docs.djangoproject.com/en/5.2/ref/models/querysets/#django.db.models.query.QuerySet.union

Here's a demo models.py that shows the issue:

```python
from django.db.models import Model, QuerySet, TextField


class Foo(Model):
    name = TextField(blank=False, null=False)


class Bar(Model):
    name = TextField(blank=False, null=False)


def foos_and_bars() -> QuerySet[Model, tuple[str]]:
    foos = Foo.objects.all().values_list("name")
    bars = Bar.objects.all().values_list("name")
    return foos.union(bars)
```

Here's what MyPy now has to say about this:

```shell
MyProject/models.py:15: error: Argument 1 to "union" of "QuerySet" has incompatible type "QuerySet[Bar, tuple[str]]"; expected "QuerySet[Model, Model]"  [arg-type]
```

I think the change that has introduced this behaviour is here:
https://github.com/typeddjango/django-stubs/commit/0087c115eda656f6fdc1faea0727a6a6fc2e47bb

The stub for `union` changed from:
`def union(self, *other_qs: Any, all: bool = False) -> Self: ...`
to:
`def union(self, *other_qs: QuerySet[Model], all: bool = False) -> Self: ...`

It looks like this new annotation for `*other_qs` is too narrow to allow for the output of the `qs.values_list()` method, even though this is the recommended pattern for using `qs.union()`.

A similar issue might now affect `qs.intersection()` and `qs.difference()`, but I haven't checked these myself.

## System information

- OS: MacOS Sequoia 15.6.1
- `python` version: 3.13.7 
- `django` version: 5.2.6
- `mypy` version: 1.18.1
- `django-stubs` version: 5.2.3
- `django-stubs-ext` version:

**Comment by sobolevn** [comment]
I am open for the revert PR :) 
Thanks for the report!

**Comment by UnknownPlatypus** [comment]
> I am open for the revert PR :)

I believe `QuerySet[Model, Any]` would me more accurate, the issue is that with the typevar default, `QuerySet[Model]` becomes `QuerySet[Model, Model]` which is no longer compatible with values list

**Comment by sobolevn** [comment]
Let's try this if it works - I am also fine with that :)
