### PR TITLE
Support processing of other relations and fields when one is broken

### LINKED ISSUE #1872: Regression: related fields raise [attr-defined]
# Bug report

With `django-stubs==4.2.7`, reports `[attr-defined]` for related fields of models. This works fine with `django-stubs==4.2.6`.

## What's wrong

Related fields are reported as undefined.

## How is that should be

Related fields should raise no error.

## System information

- OS: Alpine Linux Edge
- `python` version: 3.10 or 3.11
- `django` version: 4.2.8
- `mypy` version: `mypy 1.6.1 (compiled: no)`
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

## Reproduction scenario

This can easiest be reproduced with this repository:

    https://github.com/WhyNotHugo/django-afip.git

Currently, `main` is `3fcc7d4e3d3d0b8b201f9bc7ab35f52c003a852c`. Relevant dependencies can be installed with `pip install -e '.[dev]'`.

```console
> mypy .
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
django_afip/pdf.py:59: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
django_afip/pdf.py:195: error: "Receipt" has no attribute "entries"  [attr-defined]
django_afip/models.py:1250: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
django_afip/models.py:1308: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
django_afip/admin.py:269: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
Found 5 errors in 3 files (checked 61 source files)
> pip install "django-stubs[compatible-mypy]==4.2.6"
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
Success: no issues found in 61 source files
```

As can be seen, this was not a problem with 4.2.6.

### PR DESCRIPTION
**Pull request by flaeppe**
# I have made things!

Handles failing/erroneous reverse relations more gracefully

## Related issues

Closes: #1872 (more closely https://github.com/typeddjango/django-stubs/issues/1872#issuecomment-1851796924)

### CODE REVIEW

**Comment by flaeppe** [comment]
Unfortunately git doesn't pick up that well on moving and de-indent. The actual diff isn't really that large

**Comment by flaeppe** [comment]
These changes have been marinating for some time. I'll go ahead and merge them, since all that should happen here is that we bug fix and cover more ground/an additional case.
