### ISSUE TITLE
Setting objects manager: "Cannot override class variable with instance variable"

### ISSUE THREAD

**Issue by orsinium** [typeddjango/django-stubs#1712]
# Bug report

## What's wrong

```python
class User(AbstractUser):
    objects = UserManager()
```

Fails mypy with:

```
users/models.py:751: error: Cannot override class variable (previously declared on base class "AbstractUser") with instance variable  [misc]
```

## How is that should be

It sohuldn't produce an error, that's a valid and working Django code. It worked with django-stubs 4.2.3.

## System information

- OS: linux
- `python` version: `3.8`
- `django` version: 4.2.4
- `mypy` version: 1.5.1
- `django-stubs` version: 4.2.4
- `django-stubs-ext` version: 4.2.2

**Comment by flaeppe** [comment]
Managers are now `ClassVar`s, ref: #1672

```python
objects: ClassVar[UserManager] = UserManager()
```

**Comment by orsinium** [comment]
It works 👍🏿  I'm a bit confused, though, why setting a class attribute is interpreted by mypy as "instance variable". I define it on the class-level and don't change the type signature. For example, something like this always worked for me:

```python
class BaseMessage:
    type: ClassVar[str]

class EmailMessage(BaseMessage):
    type = "email"
```

**Comment by flaeppe** [comment]
That's probably because a string is immutable etc. if you try the same thing with a custom class and an instance of it. The error will appear.

If you read the error message quite carefully you see it says "[...] class variable [...] with instance variable".

Mypy wants you to declare that this mutable object is indeed intended as a class variable. At least that's how I read it

**Comment by craigds** [comment]
I'm getting this error and I don't understand it. The above doesn't really describe what's going on.

Here's a mutable class variable which is overridden, which works fine in mypy (0.14.1)

```python
from typing import ClassVar


class A:
    myclassvar: ClassVar[dict[str, str]] = {"my": "value"}


class B(A):
    myclassvar = {"new": "value"}
```

The equivalent thing with managers doesn't work:

```python
from django.db import models


class CustomManager(models.Manager): ...


class A(models.Model):
    x: ClassVar[models.Manager] = models.Manager()


class B(A):
    x = CustomManager()
```


results in:

```
Cannot override class variable (previously declared on base class "A") with instance variable  [misc]
```

Some observations:
* Changing `models.Manager` in the above snippet to `models.Queryset` causes the check to _pass_, so this is very specific to managers.
* Changing `objects` to any other name doesn't cause the check to pass, so it's not specific to a particular variable name.
