### ISSUE TITLE
Dynamic settings fail as of 1.13.0

### ISSUE THREAD

**Issue by markedwards** [typeddjango/django-stubs#1276]
# Bug report

## What's wrong

We build Django settings dynamically, instead of using a `settings.py` file with static properties.  This worked fine with django-stubs up until 1.13.0, but all of our settings fail with 1.13.0:

```
'Settings' object has no attribute 'FOO'
```

This seems to be caused by #1163.

## How is that should be

I understand the reasoning given in #1163, but we are pinned at django-stubs 1.12.0 and would have to completely reimplement our installation in order to unblock.  Can dynamically-constructed settings be supported with django-stubs, or is that door permanently closed?  Maybe it could be a non-default option we could enable, accepting the potential downsides?

## System information

- OS:
- `python` version: 3.10.8
- `django` version: 4.1.3
- `mypy` version: 0.991
- `django-stubs` version: 1.13.0
- `django-stubs-ext` version: 0.7.0

**Comment by virtualxdriver** [comment]
This notably breaks projects that make use of `django-configurations`.

**Comment by BranislavBajuzik** [comment]
This also breaks projects that use [`django-split-settings`](https://github.com/wemake-services/django-split-settings).

**Comment by intgr** [comment]
@sobolevn What do you think a proper solution for this issue would look like?

Being able to toggle disable the `django.conf.settings` integration in the mypy plugin would be one solution. Are there any alternatives that you can think of?

I know you have spoken against making the plugin more configurable. But IME the django-stubs plugin code is frequently fragile and causes mypy crashes ([backlog of mypy-plugin issues](https://github.com/typeddjango/django-stubs/labels/mypy-plugin)). Being able to toggle off and on certain parts of the plugin would seem helpful and allow users to pick which parts they like even if other parts don't work for them. It might also help in debugging/localizing which part of plugin code is at fault.
