### ISSUE TITLE
Regression: related fields raise [attr-defined]

### ISSUE THREAD

**Issue by WhyNotHugo** [typeddjango/django-stubs#1872]
# Bug report

With `django-stubs==4.2.7`, reports `[attr-defined]` for related fields of models. This works fine with `django-stubs==4.2.6`.

## What's wrong

Related fields are reported as undefined.

## How is that should be

Related fields should raise no error.

## System information

- OS: Alpine Linux Edge
- `python` version: 3.10 or 3.11
- `django` version: 4.2.8
- `mypy` version: `mypy 1.6.1 (compiled: no)`
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

## Reproduction scenario

This can easiest be reproduced with this repository:

    https://github.com/WhyNotHugo/django-afip.git

Currently, `main` is `3fcc7d4e3d3d0b8b201f9bc7ab35f52c003a852c`. Relevant dependencies can be installed with `pip install -e '.[dev]'`.

```console
> mypy .
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
django_afip/pdf.py:59: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
django_afip/pdf.py:195: error: "Receipt" has no attribute "entries"  [attr-defined]
django_afip/models.py:1250: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
django_afip/models.py:1308: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
django_afip/admin.py:269: error: "Receipt" has no attribute "validation"; maybe "validate"?  [attr-defined]
Found 5 errors in 3 files (checked 61 source files)
> pip install "django-stubs[compatible-mypy]==4.2.6"
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
Success: no issues found in 61 source files
```

As can be seen, this was not a problem with 4.2.6.

**Comment by flaeppe** [comment]
Thanks for reporting.

I ran git bisect and managed to pin point the issue being introduced in 53cdbe4c9e31a491378e027f08c6b5421a843958 (#1805)

**Comment by flaeppe** [comment]
@WhyNotHugo I think I found the issue. It's a bit of a hidden one, this: #1802 

I found the following `ManyToManyField` on your `Receipt` model: https://github.com/WhyNotHugo/django-afip/blob/2ba5a097d00c1f9de174678d14bd0d1eac696377/django_afip/models.py#L1198-L1203

If you apply the patch in https://github.com/typeddjango/django-stubs/issues/1802#issuecomment-1781423719 (`"Receipt"`-> `"afip.Receipt"` I believe) you should get successful runs again.

Although there's still improvements we want from this report. The not so obvious issue is that our plugin processing of the model bails hard and almost invisibly on 1 of the model attributes, which skips any remaining correct or incorrect ones.

We should be a bit more graceful and attempt to process _all_ attributes individually and bail if we encountered any we couldn't resolve appropriately. That would also have been a resolution to this issue, essentially some form of "decoupling" within `mypy_django_plugin.transformers.models.AddReverseLookups.run_with_model_cls`, which can be seen was changed in #1805

**Comment by WhyNotHugo** [comment]
I think it is safe to close this issue in favour of the ones that you've mentioned.

Thanks for bisecting this and thanks for the detailed explanation on the issue.
