### ISSUE TITLE
error: Value of type variable "_DisplayCallableT" of function cannot be "Callable[[ReceiptAdmin, HttpRequest, _QuerySet[Receipt, Receipt]], None]"

### ISSUE THREAD

**Issue by WhyNotHugo** [typeddjango/django-stubs#1569]
# Bug report

For this admin action:

https://github.com/WhyNotHugo/django-afip/blob/3e53e49c45af195a1553313a85485da2f283363b/django_afip/admin.py#L244-L258

I'm getting the error:

```
django_afip/admin.py:244: error: Value of type variable "_DisplayCallableT" of function cannot be "Callable[[ReceiptAdmin, HttpRequest, _QuerySet[Receipt, Receipt]], None]"  [type-var]
```

## What's wrong

As far as I can tell, this usage is correct. The error is not entirely clear to me, although I think the lack of clarify in the error is a `mypy` issue (e.g.: it doesn't indicate **why** this type is unacceptable).

## How is that should be

This usage is valid.

## Additional notes

[This worked on `django_stubs-4.2.0`](https://github.com/WhyNotHugo/django-afip/actions/runs/4975355186/jobs/8902451166).

## System information

- `python` version: 3.10 or 3.11
- `django` version: Django-4.2.2
- `mypy` version: mypy-1.4.0 or mypy-1.3.0
- `django-stubs` version: django_stubs-4.2.1
- `django-stubs-ext` version: django-stubs-ext>=4.2.1

**Comment by WhyNotHugo** [comment]
Ugh, never mind, I mixed up `@display` and `@action`.
